name: Integrate
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-24.04
    name: Lint
    steps:
      - uses: holepunchto/actions/python-base@v1
      - run: ruff format --check .
      - run: ruff check .
  test:
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    runs-on: ubuntu-24.04
    name: Test / ${{ matrix.python-version }}
    steps:
      - uses: holepunchto/actions/python-base@v1
        with:
          python-version: ${{ matrix.python-version }}
      - run: pytest
